# Beryllium

[keys]
host       =  "ğŸš  host"
machine    =  "ğŸ’» machine" 
kernel     =  "âš™ï¸  kernel"
# distro     =  "â‡  distro"
packages   =  "ğŸ“¦ packages"
terminal   =  "ğŸ—”  terminal"
shell      =  "ê©œ  shell"
cpu        =  "âš”  cpu"
cpu_load   =  "ğŸ“ˆ cpu load"
memory     =  "âš”  memory"
battery    =  "ğŸ”‹ battery"
uptime     =  "â±ï¸  uptime"
resolution =  "ğŸ“½  resolution"
backlight  =  "ğŸ•¯ï¸  brightness"
de         =  "ğŸ’» de"
wm         =  "ğŸ——  wm"
